const express = require('express')
const app = express()
const http = require('http')
const server = http.createServer(app)

const cors = require('cors')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser');

const ConnectDB = require('./DBConnect') //DB connection

app.use(cors({
    origin: 'http://localhost:3000',
    credentials: true
}))
app.use(express.json({limit:'10mb'}))
app.use(bodyParser.urlencoded({ extended: true }))
app.use(cookieParser())

// router
const CollegeRegisterRoute = require('./Routers/College_Register_Route')
const Fetch_Data = require('./Routers/Fetch_Data')
const Admin_Signin = require('./Routers/AdminSignin')
const fetch_college_application = require('./Routers/Fetch_college_applications')
const Tacke_Action = require('./Routers/Take_ActionOnCollegeApplication')
const Add_Course = require('./Routers/Add_Course')
const Get_College_Courses = require('./Routers/Get_College_Courses')
const Update_Course = require('./Routers/Update_Course')
const Add_Gallery = require('./Routers/AddGallery')
const Get_College_Gallery = require('./Routers/GetCollegeGallery')
const Delete_Gallery = require('./Routers/DeleteGallery')
const UpdateProfile = require('./Routers/UpdateProfile')
const User_Register = require('./Routers/User_Register')
const Search_College = require('./Routers/SearchCollege')
const Explore_Program = require('./Routers/ExploreProgram')
const Get_Course_By_Program = require('./Routers/GetProgramCourse')
const Get_College_By_Course = require('./Routers/GetCollegeByCourse')
const College_Overview_Basic = require('./Routers/CollegeOverviewBasic')
const College_Overview_Course = require('./Routers/CollegeOverviewCourse')
const College_Overview_Gallery = require('./Routers/CollegeOverviewGallery')
const College_Overview_review = require('./Routers/CollegeOvervieReview')
const Leave_Review = require('./Routers/LeaveReview')
const SignUp_And_Create_Application = require('./Routers/SignupAndCreateApplication')
const User_SignIn = require('./Routers/UserSingIn')
const GetUser_Application = require('./Routers/GetUser_Applications')
const Admin_Dashboard = require('./Routers/Admin_Dashboard_data')
const User_Application_At_Dashboard = require('./Routers/UserApplicationsAtDashboard')
const Take_Action_On_User_Application = require('./Routers/TakeActionOnUserApplication')
const Get_User_Enquiry_At_Dashboard = require('./Routers/GetUserEnquiryAtDashboard')
const Take_Action_On_Enquiry = require('./Routers/TakeActionOnEnquiry')
const Add_New_Couselor = require('./Routers/AddNewCounselor')
const Get_All_Counselor = require('./Routers/GetAllCounselor')
const Get_Counselor_Data = require('./Routers/GetCounselorDataAtAdmin')
const Update_Counselor_profile = require('./Routers/Update_Counselor_Profile')
const College_SignIn = require('./Routers/CollegeSignIn')
const Update_Email = require('./Routers/UpdateEmail')
const Update_Phone = require('./Routers/UpdatePhone')
const Update_Password = require('./Routers/UpdatePassword')
const Counselor_SignIn = require('./Routers/CounselorSignIn')
const Update_Profile_Pic = require('./Routers/UpdateProfilePic')
const College_List = require('./Routers/CollegeList')
const Create_New_Quetion = require('./Routers/CreateNewQuestion')
const GetAllQuestion = require('./Routers/GetAllQuestion')
const Dlt_Question = require('./Routers/DltQuestion')
const Tier_Action = require('./Routers/TierAction')
const Forget_Password = require('./Routers/ForgetPassword')
const Top_University = require('./Routers/TopUniversity')
const All_Counselor = require('./Routers/AllCounselorAtUser') //at home page
const Counselor_Overview_Details = require('./Routers/CounselorOverviewDetails')
const Counselor_Review = require('./Routers/AddCounselorReview')
const Counselor_Call_Request = require('./Routers/CounselorCallRequest')
const Get_Call_Request = require('./Routers/GetCounselorCallRequest')  //at admin panel
const Take_Action_On_Request = require('./Routers/TakeActionOnCallRequest')

// user routers
app.post('/college_register', CollegeRegisterRoute)
app.post('/getdata', Fetch_Data)
app.post('/adminsignin', Admin_Signin)
app.post('/collegeapplications', fetch_college_application)
app.patch('/tackaction', Tacke_Action)
app.post('/addcourse', Add_Course)
app.post('/getcollegecourse', Get_College_Courses)
app.patch('/updatecourse', Update_Course)
app.post('/addgallery', Add_Gallery)
app.post('/getcollegegallery', Get_College_Gallery)
app.delete('/deletegallery/:postId', Delete_Gallery)
app.patch('/updateProfile', UpdateProfile)
app.post('/user_register', User_Register)
app.post('/searchcollege', Search_College)
app.post('/exploreprogram', Explore_Program)
app.post('/getcourseByprogram', Get_Course_By_Program)
app.post('/getcollegBycourse', Get_College_By_Course)
app.get('/collegeoverviewbasic/:collegeId', College_Overview_Basic)
app.get('/collegeoverviewcourse/:collegeId', College_Overview_Course)
app.get('/collegeoverviewgallery/:collegeId', College_Overview_Gallery)
app.get('/collegeoverviewreview/:collegeId', College_Overview_review)
app.post('/leavereview', Leave_Review)
app.post('/singupandcreateapplication', SignUp_And_Create_Application)
app.post('/usersignin', User_SignIn)
app.post('/getuser_application', GetUser_Application)
app.post('/adminpaneldata', Admin_Dashboard)
app.post('/userapplication_atdashboard', User_Application_At_Dashboard)
app.patch('/takeactionOnuser', Take_Action_On_User_Application)
app.post('/userenquiry_Atdashboard', Get_User_Enquiry_At_Dashboard)
app.patch('/takeactionOnenquiry', Take_Action_On_Enquiry)
app.post('/addnewcounselor', Add_New_Couselor)
app.post('/getAllcounselor', Get_All_Counselor)
app.post('/getcounselordata/:_id', Get_Counselor_Data)
app.patch('/update_counselor_profile', Update_Counselor_profile)
app.post('/college_signin', College_SignIn)
app.post('/request-email-update', Update_Email)
app.patch('/verify-email-update', Update_Email)
app.post('/request-phone-update', Update_Phone)
app.patch('/verify-phone-update', Update_Phone)
app.post('/request-password-update', Update_Password)
app.patch('/verify-password-update', Update_Password)
app.post('/counselor_signIn', Counselor_SignIn)
app.patch('/updateProfilePic', Update_Profile_Pic)
app.post('/collegeList', College_List)
app.post('/createnewQuestion', Create_New_Quetion) 
app.post('/getAllQuestion', GetAllQuestion)
app.delete('/dltQuesti/collegeIdon/:questionId', Dlt_Question)
app.patch('/tierAction/:collegeId', Tier_Action)
app.post('/request-Forgot-Password', Forget_Password)
app.patch('/verify-forgot-password', Forget_Password)
app.post('/topUniversity', Top_University)
app.post('/counselors', All_Counselor)
app.post('/counselorOverviewDetails/:counselorId', Counselor_Overview_Details)
app.post('/counselorReview', Counselor_Review)
app.post('/counselorCallRequest', Counselor_Call_Request)
app.post('/getCallrequest', Get_Call_Request)
app.patch('/requestAction/:requestId', Take_Action_On_Request)

// listen server
server.listen(8000, () => {
    console.log('Server is started')
})